# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29675ca769c054ad184c0eda5f5e280bc78bbd957489babea8ef4b844689002a56cbe2e0f0233d44ab1ad1c4df90f274b363ffe303f098f4847e5a1107a80d02

test:
  secret_key_base: 819ce3ed68b0fd71e32345fd9dfbb845ad2a912bafd29136dd3ffa0a28f631ba8761af8d3000bffc5eeaab6153ef335fbc219d6304e0302372ae955fbe523aa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
